### PR TITLE
pytest 4.1 compatibility fixes

### LINKED ISSUE #89: Pytest4 errors - previously deprecated stuff is now Error
Related pages:
https://docs.pytest.org/en/latest/deprecations.html#cached-setup
https://github.com/pytest-dev/pytest/blob/master/CHANGELOG.rst#deprecations-1

AttributeError: 'SubRequest' object has no attribute 'cached_setup'
```
    @pytest.fixture
    def gw(request, execmodel):
        scope = request.config.option.scope
>       group = request.cached_setup(
            setup=execnet.Group,
            teardown=lambda group: group.terminate(timeout=1),
            extrakey="testgroup",
            scope=scope,
        )
E       AttributeError: 'SubRequest' object has no attribute 'cached_setup'
```

RemovedInPytest4Warning: getfuncargvalue is deprecated, use getfixturevalue
```
    @pytest.fixture
    def anypython(request):
        name = request.param
        executable = getexecutable(name)
        if executable is None:
            if sys.platform == "win32":
                executable = winpymap.get(name, None)
                if executable:
                    executable = py.path.local(executable)
                    if executable.check():
                        return executable
                    executable = None
            py.test.skip("no %s found" % (name,))
        if "execmodel" in request.fixturenames and name != 'sys.executable':
>           backend = request.getfuncargvalue("execmodel").backend
E           RemovedInPytest4Warning: getfuncargvalue is deprecated, use getfixturevalue

testing/conftest.py:152: RemovedInPytest4Warning
______________ ERROR at setup of test_popen_io[thread-python2.7] _______________
```

### PR DESCRIPTION
**Pull request by nicoddemus**
Fix #89

### CODE REVIEW

**Comment by hroncok** [comment]
@nicoddemus Hi, any chance for a released version with this? Thanks

**Comment by nicoddemus** [comment]
Hi @hroncok, unfortunately I don't have publishing rights to `execnet`. @RonnyPfannschmidt could you give me access to PyPI please?

**Comment by hroncok** [comment]
Don't worry about it too much, we can patch.

**Comment by RonnyPfannschmidt** [comment]
perms are out

**Comment by nicoddemus** [comment]
@hroncok 1.6.0 is out. 👍

**Pull request merged**
