### PR TITLE
Replace "slave" terminology

### PR DESCRIPTION
**Pull request by Zac-HD**
See https://github.com/pytest-dev/pytest/issues/7344.

This is *mostly* internal, with the possible exception of renaming `SlaveGateway` to `WorkerGateway`... I'm going for the optimistic change first though, it's easy to roll back to a partial fix if we need to.

### CODE REVIEW

**Comment by nicoddemus** [comment]
Thanks @Zac-HD!

Seems like a test still uses `SlaveGateway`:

```
____________________________ test_exectask[thread] ____________________________
execmodel = <ExecModel 'thread'>
    def test_exectask(execmodel):
        io = py.io.BytesIO()
        io.execmodel = execmodel
>       gw = gateway_base.SlaveGateway(io, id="something")
E       AttributeError: 'module' object has no attribute 'SlaveGateway'
testing\test_basics.py:285: AttributeError
```

**Comment by Zac-HD** [comment]
Thanks @nicoddemus ... I forgot to grep case-insensitive :man_facepalming:  Fixed now.

**Comment by Zac-HD** [comment]
@nicoddemus - what are the next steps for this?  I don't have permissions to merge it or cut a release, but if there's something I can do I'm happy to help.

**Comment by nicoddemus** [comment]
Not sure, this is definitely a breaking change... We probably should release a new pytest-xdist version pinning to execnet <2.0, then a new pytest-xdist version which supports execnet >=1.0 (probably falling back to use the SlaveGateway name when in execnet <2.0). @RonnyPfannschmidt what do you think?

**Comment by RonnyPfannschmidt** [comment]
AFAIK xdist doesn't depend on the name, let's crosscheck and if there is no dependency, no pin in xdist

**Comment by nicoddemus** [comment]
Ahh it seems you are right, `SlaveGateway` is not explicitly referenced anywhere. 👍

**Comment by Zac-HD** [comment]
@nicoddemus @RonnyPfannschmidt are we ready to merge then?

**Comment by RonnyPfannschmidt** [comment]
I think so

**Comment by nicoddemus** [comment]
Thanks @Zac-HD!

**Pull request merged**
