### PR TITLE
fix(socketserver): current workdir be modified when loop =True

### PR DESCRIPTION
**Pull request by yili1992**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Hi @yili1992,

Thanks for the PR.

Can you please describe what your change is fixing, and also to include a test?

**Comment by yili1992** [comment]
> Hi @yili1992,
> 
> Thanks for the PR.
> 
> Can you please describe what your change is fixing, and also to include a test?

In my case , i use pytest-xdist to run testcase in remote server, i set the loop is True in [socketserver.py](https://github.com/pytest-dev/execnet/blob/master/execnet/script/socketserver.py) line:129
my pytest run command:
`-d --tx socket=x.x.x.x:8888 --rsyncdir mypkg`
my first execution, mypkg is synced to remote server directory:
`/Users/zhaoli/Documents/B.03Code_Space/Pyspace/execnet/execnet/script/pyexecnetcache`
my second execution mypkg is synced to remote server directory:
`/Users/zhaoli/Documents/B.03Code_Space/Pyspace/execnet/execnet/script/pyexecnetcache/pyexecnetcache`

Therefore, the purpose of this PR is to ensure that the workdir of socketserver remains unchanged

**Comment by nicoddemus** [comment]
Thanks @yili1992 and sorry for the delay!

**Comment by nicoddemus** [comment]
`1.8.0` released! 🎉

**Pull request merged**
